### ISSUE TITLE
Support for Monad Transformer stacks?

### ISSUE THREAD

**Issue by benhutchison** [typelevel/cats-effect-cps#145]
I initially tried out this library with success in an CE3 `IO` based project.

In some modules I use monad stacks such as `WriterT` over `IO` (with cats-mtl).

When I try to use a stack with `await`, I get a compile error about  
```
/* missing */
[error]    |        summon[
[error]    |          cps.CpsMonadContext[
[error]    |            [_] =>>
[error]    |              cats.data.WriterT[cats.effect.IO,
[error]    |                cats.data.Chain[LogRecord], _]
[error]    |          ]
[error]    |        ]
```

Im confident that `Async` is available for `WriterT` over `IO`, but Im unsure if I should expect `CpsMonadContext` to be derived for a monad stack? I note the readme example is for just plain `IO`.

**Comment by djspiewak** [comment]
Good question! By the error I infer you're using Scala 3, which is good since Writer almost certainly won't work sanely with this library on Scala 2. I'll poke around with it. Honestly, I would expect it to work.

**Comment by Baccata** [comment]
_cough_

https://github.com/typelevel/cats-effect-cps/blob/main/core/shared/src/test/scala/cats/effect/cps/AsyncAwaitSpec.scala#L195

**Comment by Baccata** [comment]
@benhutchison any chance you can provide a minified repro ?

**Comment by benhutchison** [comment]
Let me investigate the diff between that working unit test and my context. Most likely its a mistake on my part. But if there's more to it, I'll report back..

**Comment by benhutchison** [comment]
Solved. Problem between keyboard and chair.

I was a curious manifestation, so for the benefit of anyone else who comes along, my mistake was to try to destructure the result, like so:

```
val (program, log) = async[F](io1.await)
```

but doh, that's now how Writer monads work. You have to `run` the whole program to see the logs.

**Comment by Baccata** [comment]
Haha, fair enough. No judgement here, I make silly mistakes all the freaking time. Thanks for the update !
