### ISSUE TITLE
Adjust `AsyncAwaitDsl` to `http4s` style

### ISSUE THREAD

**Issue by vasilmkd** [typelevel/cats-effect-cps#7]
(Re-opening https://github.com/typelevel/cats-effect/issues/2039).

```scala
val dsl = AsyncAwaitDsl[IO]
import dsl._
```
This is a bit more uniform with http4s, and also has the advantage of being more concise.

**Comment by djspiewak** [comment]
Oh, actually this is obsolete now since we don't have the `dsl` import at all.
