### ISSUE TITLE
Sync support if possible

### ISSUE THREAD

**Issue by djx314** [typelevel/cats-effect-cps#75]
Since `doobie.ConnectionIO` just can provide `summon[Sync[ConnectionIO]]`, so I can't simply use cats-effect-cps in `ConnectionIO`. Is there any support if possible?

**Comment by Baccata** [comment]
In Scala 2 it is simply impossible, due to the constraints required to create a [Dispatcher](https://github.com/typelevel/cats-effect/blob/series/3.x/std/shared/src/main/scala/cats/effect/std/Dispatcher.scala#L102) which is required to interop with the async/await mechanism built in the Scala 2 compiler. 

In Scala 3 it'd be possible. The Scala 3 implementation is built on top of [dotty-cps-async](https://github.com/rssh/dotty-cps-async), which has different abstractions that you can tap into, one that can be virtually implemented for [any monadic construct](https://github.com/rssh/dotty-cps-async/blob/master/shared/src/main/scala/cps/CpsMonad.scala#L20)

**Comment by djspiewak** [comment]
Can confirm that fixing that todo would make a lot of this functionality usable with `Sync`, but only on Scala 3. The way the Scala 2 stuff is done outright requires `Async`, as Oli noted.

**Comment by djx314** [comment]
Thanks a lot! Coincidentally, our current requirements are based on scala3.

**Comment by djspiewak** [comment]
> Coincidentally, our current requirements are based on scala3.

Then you're in luck! Unfortunately, I don't really have the time to work on resolving this right now, but I would try to review and merge pull requests if you're interested in diving in! It's not a particularly complex change. If you're interested, jump to the TODO Oli linked above. Right now, we just do a single big instance that requires `Async` and provides everything. However, `CpsConcurrentEffectMonad` actually extends less powerful instances which could, themselves, be materialized using less powerful typeclasses (such as `Concurrent` or `MonadCancel` or even `Monad`). What needs to happen is for the `cps` object to extend `LowPriorityInstances1`, which extends `LowPriorityInstances2`, etc etc as far as you need to go, with each one containing a successively *less* powerful instance (e.g. maybe `LowPriorityInstances1` materializes a less powerful `Cps` typeclass based on `Concurrent`, while `LowPriorityInstances2` materializes a still-less-powerful one based on `Spawn`, and `LowPriorityInstances3` an even less powerful one based on `MonadCancel`, etc etc). You can use inheritance to eliminate duplication between instances. This isn't the *greatest* example, but you can get an idea of how this works by looking at how the monad transformer instances are implemented in Cats Effect (note the inheritance): https://github.com/typelevel/cats-effect/blob/series/3.x/kernel/shared/src/main/scala/cats/effect/kernel/Async.scala#L259 Another source of inspiration that's a bit more directly applicable can be found in my old shims project: https://github.com/djspiewak/shims/blob/master/core/src/main/scala/shims/conversions/monad.scala#L373

Make sure to write some tests which show that we can use limited forms of the syntactic transformation given weaker constraints in scope!

**Comment by djx314** [comment]
Thank you for the detailed guidance! After solving the health problem, I think I can have a try.
